### ISSUE TITLE
NMI_BIT, IRQ_BIT, FIQ_BIT values

### ISSUE THREAD

**Issue by speriator** [smittytone/e6809#1]
this values are defined in cpu.h

#define NMI_BIT                 0
#define IRQ_BIT                 1
#define FIRQ_BIT                2

but I don't understand how this values can handle normally the interrupts in the process_next_instruction() method.

you have  if (state.wait_for_interrupt || state.interrupts > 0) --> so must be >0 : OK. because value are 1 - 2 or 4

but you have later 

if (state.interrupts & NMI_BIT) --> ZERO;

maybe the correct values are 

#define NMI_BIT                 1
#define IRQ_BIT                 2
#define FIRQ_BIT                4

??

**Comment by smittytone** [comment]
You’re right, but I want retain those constants as bit numbers rather than byte values, so I'll update the code accordingly.
