### ISSUE TITLE
Bad implementation of JMP opcode 7E

### ISSUE THREAD

**Issue by speriator** [smittytone/e6809#3]
bad implementation of jmp() in cpu.c, the extended mode gives a bad adress.

I think it must be implemented as jsr() is, without stacking.

void jmp(uint8_t mode) {
    uint16_t address = address_from_mode(mode);
    // old implementation -> reg.pc = (mode == MODE_INDEXED) ? address : ((get_byte(address) << 8) | get_byte(address + 1));
    reg.pc = address;

}

**Comment by smittytone** [comment]
`address_from_mode()` provides the address when extended, so we don't need the line as is: your correction is correct. Will update, test and push
