### ISSUE TITLE
issue in st16(...) method

### ISSUE THREAD

**Issue by speriator** [smittytone/e6809#4]
the method touch the B register where it must not.

void st_16(uint8_t op, uint8_t mode, uint8_t ex_op) {
...

   } else {
        reg.d = (reg.a << 8) | reg.d;      // ERROR think it must be reg.d = (reg.a << 8) | reg.d; 
        reg_ptr = &reg.d;
        touched_d = true;
    }

   if (touched_d) {                               // why this code ?
        reg.b = reg.d & 0xFF;
        reg.a = (reg.d >> 8) & 0xFF;
    }
...
}

**Comment by smittytone** [comment]
Some old code left there, I think. Will remove
