### ISSUE TITLE
Issue on OPCODE BC extended mode

### ISSUE THREAD

**Issue by speriator** [smittytone/e6809#5]
I have an issue with the opcode BC, the next byte code for next instruction is disappearing

the pc must not be incremented when mode is extended.
Not sure of my correction.

void cmp_16(uint8_t op, uint8_t mode, uint8_t ex_op) {
   ...

    // 'addressFromMode:' assumes an 8-bit read, so we need to increase PC by 1
    if(mode!=MODE_EXTENDED)reg.pc++; ////<------------------------------------------------- 

   ...

}

**Comment by smittytone** [comment]
Checking, `address_from_mode()` directly or indirectly via calls moves the PC on by one, two or more bytes, so we don't need that `reg.PC++` line at all. Will update, test and push
