### ISSUE TITLE
LDD imm opcode CC 

### ISSUE THREAD

**Issue by speriator** [smittytone/e6809#6]
opcode CC is not going to the ld_16 method, because of this

        if (lsn == 0x0C) {
            if (msn < 0x08) {
                inc(opcode, address_mode);
            } else if (msn >= 0x0C) {. /////// <------  HERE is the mistake
                // LDD
                ld_16(opcode, address_mode, extended_opcode);
            } else {
                cmp_16(opcode, address_mode, extended_opcode);
            }

            return cycles_used;
        }

**Comment by smittytone** [comment]
/
